# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "environment"
        options: 
        - dev
        - staging
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environment }}
    steps:
      - name: Run a one-line script
        run: echo "ENV ${{ inputs.environment }}  ;  FF ${{ vars.FF }}"
